"""Domain models and typed ontology definitions."""

from fde_workbench.domain.ontology import EntityTypeEnum, RelationTypeEnum, ONTOLOGY_METADATA
from fde_workbench.domain.entities import (
    BaseEntity,
    Organization,
    Facility,
    Supplier,
    Customer,
    Product,
    Material,
    Order,
    PurchaseOrder,
    Shipment,
    Carrier,
    Warehouse,
    Invoice,
    Payment,
    Contract,
    Document,
    CustomsDeclaration,
    RegulatoryObligation,
    EmployeeRole,
    Machine,
    ProductionBatch,
    QualityEvent,
    OperationalEvent,
    Decision,
    KPI,
    ENTITY_TYPE_TO_CLASS,
)
from fde_workbench.domain.relationships import Relationship, ALLOWED_RELATIONSHIPS
from fde_workbench.domain.events import EventSeverity, EventStatus
from fde_workbench.domain.decisions import DecisionOption, AuthorizedAction, DecisionOutcome
from fde_workbench.domain.ai_opportunities import AIOpportunity, DeploymentComplexity
from fde_workbench.domain.agent_specs import AgentSpecification, ToolDefinition

__all__ = [
    "EntityTypeEnum",
    "RelationTypeEnum",
    "ONTOLOGY_METADATA",
    "BaseEntity",
    "Organization",
    "Facility",
    "Supplier",
    "Customer",
    "Product",
    "Material",
    "Order",
    "PurchaseOrder",
    "Shipment",
    "Carrier",
    "Warehouse",
    "Invoice",
    "Payment",
    "Contract",
    "Document",
    "CustomsDeclaration",
    "RegulatoryObligation",
    "EmployeeRole",
    "Machine",
    "ProductionBatch",
    "QualityEvent",
    "OperationalEvent",
    "Decision",
    "KPI",
    "ENTITY_TYPE_TO_CLASS",
    "Relationship",
    "ALLOWED_RELATIONSHIPS",
    "EventSeverity",
    "EventStatus",
    "DecisionOption",
    "AuthorizedAction",
    "DecisionOutcome",
    "AIOpportunity",
    "DeploymentComplexity",
    "AgentSpecification",
    "ToolDefinition",
]
